name: 'Publish Docker'
description: 'Publish to Docker'
inputs:
  docker_username:  
    description: 'Docker user'
    required: true
  docker_password:  
    description: 'Docker Password'
    required: true
  tag:  
    description: 'Image tag '
    required: true  
    default: 'user/app:latest'
outputs:
  imageid:
    description: "Docker Image Id"
    value: ${{ steps.push.outputs.imageid }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}
    - name: Build Docker Image Locally
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags:  |
            ${{ inputs.tag }}
    - name: Inspect the Docker Image
      shell: bash
      run: |
        docker image inspect ${{ inputs.tag }}
    - name: Run Functional Tests
      id: functionaltest
      shell: bash
      run: |
          docker run -d -p 80:80 ${{ inputs.tag }}
          sleep 5
          curl http://localhost:80
    - name: Push Docker Image
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags:  |
            ${{ inputs.tag }}  
