name: 'Publish Docker'
description: 'Publish to Docker'
inputs:
  registry_username:  
    description: 'Docker user'
    required: true
  registry_password:  
    description: 'Docker Password'
    required: true
  tag:  
    description: 'Image tag '
    required: true  
    default: 'user/app:latest'
outputs:
  imageid:
    description: "Docker Image Id"
    value: ${{ steps.push.outputs.imageid }}
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}
      - uses: docker/build-push-action@v2
        id: push
        with:
          context: .
          push: true
          tags: ${{inputs.tag}}
