# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    secrets:
      docker_username: 
        description: Docker user
        required: true
      docker_password: 
        description: Docker password
        required: true   
    inputs:
      tag:
        description: tag
        type: string
        required: true
        default: yadhav/tic-tac-toe:latest
      
    
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/publish-docker
      with:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
        tag: ${{ inputs.tag }}
