name: Create pre-release
on:
  pull_request:
    types:
    - 'opened'
    - 'reopened'
    - 'synchronized'
    branches: 
    - 'master'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#     - name: Lint Code Base
#       uses: github/super-linter/slim@v4
#       env:
#         VALIDATE_ALL_CODEBASE: false
#         DEFAULT_BRANCH: master
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         VALIDATE_JAVASCRIPT_ES: true
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- -u
    - uses: actions/upload-artifact@v3
      with:
        name: webpack artifacts
        path: public/
        
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: codeql
      uses: ./.github/actions/codeql-analysis
      with:
        languages: 'javascript'
        
  release:
    name: pre-release
    runs-on: ubuntu-latest
    needs: [build, codeql]
    outputs:
      release: ${{ steps.rcrelease.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: Tag a rc release 
        id: rcrelease
        uses: actionsdesk/semver@0.6.0-rc.10
        with:
          bump: patch
          prerelease: withBuildNumber
          prelabel: alpha
          commitish: ${{ github.head_ref }}
  
 
