# Simple workflow for deploying static content to GitHub Pages
name: Staging Tic-Tac-Toe App 

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_JAVASCRIPT_ES: true
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- -u
    - uses: actions/upload-artifact@v3
      with:
        name: webpack artifacts
        path: public/
        
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: codeql
      uses: ./.github/actions/codeql-analysis
      with:
        languages: 'javascript'
        
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build, codeql]
    if: github.head_ref != 'master'
    outputs:
      release: ${{ steps.rcrelease.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: Tag a rc release 
        id: rcrelease
        uses: actionsdesk/semver@0.6.0-rc.10
        with:
          prerelease: withBuildNumber
          prelabel: rc
          commitish: ${{ github.head_ref }}
  
  package:
    needs: [build, codeql, release]
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: package to docker
      uses: ./.github/actions/publish-docker
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        tag: yadhav/tic-tac-toe:${{needs.release.outputs.release}}

  publish:
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: [build, codeql, package]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
