# This is a basic workflow to help you get started with Actions

name: Mergeability Checks

on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check if PR is mergeable 
        id: isMergeable
        uses: actions/github-script@v5
        with:
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const org = context.payload.organization.login
            const repo = context.payload.repository.name
            const params = {
                  owner: org,
                  repo,
                  pull_number: context.payload.pull_request.number
                }
            try {
              const res = await github.rest.pulls.get(params)
              if (res.mergeable === true) {
                 console.log("This PR is mergeable")
              }
            } catch (e) {
              if (e.status === 404) {
                const message404 = `No PR found for ${JSON.stringify(params)}`
                core.debug(message404)
                core.setOutput('status', message404)
                core.setFailed(`${message404}`)
                throw new Error(message404)
              }
              const message = `${e} fetching the PR with ${JSON.stringify(params)}`
              core.debug(message)
              core.setOutput('status', message)
              core.setFailed(`${message}`)
              throw new Error(message)
            }
